### ISSUE TITLE
When running in Xcode 15.3 getting Incompatible function pointer types passing 'YGSize (...)' exception

### ISSUE THREAD

**Issue by alex-mironov** [react-native-datetimepicker/datetimepicker#866]
# Bug report

I've updated to the most recent Xcode 15.3 and build started to fail with:
```
Incompatible function pointer types passing 'YGSize (YGNodeRef, float, YGMeasureMode, float, YGMeasureMode)' (aka 'struct YGSize (struct YGNode *, float, enum YGMeasureMode, float, enum YGMeasureMode)') to parameter of type 'YGMeasureFunc' (aka 'struct YGSize (*)(const struct YGNode *, float, enum YGMeasureMode, float, enum YGMeasureMode)')
```
Any idea what can be wrong with it?

Getting the issue 
<img width="1116" alt="image" src="https://github.com/react-native-datetimepicker/datetimepicker/assets/2544767/7596e060-9d98-4a6e-b16c-008c14db46d8">

```
    "react-native": "0.73.1",
    "@react-native-community/datetimepicker": "^7.6.2",
```

**Comment by sbeigel** [comment]
Same, I changed YGNodeRef to YGNodeConstRef in RNDateTimePickerShadowView.m line 44 (in function RNDateTimePickerShadowViewMeasure) and everything seems back to normal :)

**Comment by chsdwn** [comment]
> Same, I changed YGNodeRef to YGNodeConstRef in RNDateTimePickerShadowView.m line 44 (in function RNDateTimePickerShadowViewMeasure) and everything seems back to normal :)

It fixed my build error issue too. Thank you.

**Comment by sonmybbp05** [comment]
> Same, I changed YGNodeRef to YGNodeConstRef in RNDateTimePickerShadowView.m line 44 (in function RNDateTimePickerShadowViewMeasure) and everything seems back to normal :)

It 's same issue.

**Comment by david98** [comment]
The solution proposed by @sbeigel was indeed correct, but I kept getting an error at line 4 about "an expected expression". Turns out some weird whitespace character was used, I don't know if that was my fault or what...

Anyways, this patch fixed the compilation errors:

```
diff --git a/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePicker.xcodeproj/project.xcworkspace/contents.xcworkspacedata b/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePicker.xcodeproj/project.xcworkspace/contents.xcworkspacedata
new file mode 100644
index 0000000..94b2795
--- /dev/null
+++ b/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePicker.xcodeproj/project.xcworkspace/contents.xcworkspacedata
@@ -0,0 +1,4 @@
+<?xml version="1.0" encoding="UTF-8"?>
+<Workspace
+   version = "1.0">
+</Workspace>
diff --git a/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerShadowView.m b/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerShadowView.m
index c139440..45a97dd 100644
--- a/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerShadowView.m
+++ b/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerShadowView.m
@@ -2,8 +2,7 @@
 
 @implementation RNDateTimePickerShadowView
 
-- (instancetype)init
-{
+- (instancetype)init {
   if (self = [super init]) {
     YGNodeSetMeasureFunc(self.yogaNode, RNDateTimePickerShadowViewMeasure);
   }
@@ -41,7 +40,7 @@ - (void)setTimeZoneName:(NSString *)timeZoneName {
   YGNodeMarkDirty(self.yogaNode);
 }
 
-static YGSize RNDateTimePickerShadowViewMeasure(YGNodeRef node, float width, YGMeasureMode widthMode, float height, YGMeasureMode heightMode)
+static YGSize RNDateTimePickerShadowViewMeasure(YGNodeConstRef node, float width, YGMeasureMode widthMode, float height, YGMeasureMode heightMode)
 {
   RNDateTimePickerShadowView *shadowPickerView = (__bridge RNDateTimePickerShadowView *)YGNodeGetContext(node);

```

**Comment by phicoder** [comment]
@david98 for me the proposed solution by @sbeigel was sufficient. I think the error at line 4 might have been on your end. Try to reinstall the package, implement the suggested solution and build again to avoid any confusion.

**Comment by fnazarios** [comment]
Same here. The workaround fixed the compilation error. Any clue when this will be released?

**Comment by hereusmizo** [comment]
> Same, I changed YGNodeRef to YGNodeConstRef in RNDateTimePickerShadowView.m line 44 (in function RNDateTimePickerShadowViewMeasure) and everything seems back to normal :)

Thank you so much. You save my day.

**Comment by mfrfinbox** [comment]
I am having the same issue! Changing to YGNodeConstRef fixed the problem, I would love this to be fixed soon! Thanks a lot

**Comment by therbta** [comment]
> Same, I changed YGNodeRef to YGNodeConstRef in RNDateTimePickerShadowView.m line 44 (in function RNDateTimePickerShadowViewMeasure) and everything seems back to normal :)

this did work! Thank you.

**Comment by mpho-ppm** [comment]
Got the same issue on Expo

**Comment by mphill** [comment]
@mpho-ppm the fix works on Expo too (dev client builds)

Just go to `node_modules/@react-native-community/datetimepicker/ios` and edit line 44.   `expo run:<platform> `will work again.

This is a hack workaround until a fix is released.  If you restore modules this will be overwritten.

**Comment by mphill** [comment]
@bitcrumb nice!  EAS build servers are still working because they are not using Xcode 15.3, but we may have to do this if they upgrade. Thanks for sharing this pearl.

**Comment by MariuzM** [comment]
Same for me

**Comment by MariuzM** [comment]
But i did notice when running eas build locally im getting this issue.
<img width="844" alt="image" src="https://github.com/react-native-datetimepicker/datetimepicker/assets/36937039/352c3362-51ed-42fe-a68a-cf7ca71f0134">

**Comment by aleksandar-zoric-workvivo** [comment]
Can anyone confirm applying the fix above by @sbeigel breaks it on previous versions of Xcode? i.e. is this specific to 15.3?

**Comment by Robert27** [comment]
After applying the fix and reinstalling everything, I still another error during build:
```
❌  Undefined symbols for architecture arm64
┌─ Symbol: _RNDateTimePickerCls
└─ Referenced from: _RCTThirdPartyFabricComponentsProvider in libReact-RCTFabric.a[38](RCTThirdPartyFabricComponentsProvider.o)


❌  ld: symbol(s) not found for architecture arm64
```

**Comment by MariuzM** [comment]
> > But i did notice when running eas build locally im getting this issue. <img alt="image" width="844" src="https://private-user-images.githubusercontent.com/36937039/311109551-352c3362-51ed-42fe-a68a-cf7ca71f0134.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNzY1NTksIm5iZiI6MTcxMDE3NjI1OSwicGF0aCI6Ii8zNjkzNzAzOS8zMTExMDk1NTEtMzUyYzMzNjItNTFlZC00MmZlLWE2OGEtY2Y3Y2E3MWYwMTM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDE2NTczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjYjVmMDNkYWE0MTZkNTQ1OGJiNTRlZTljMGIxODdjZDY1YmFjN2ExNTQyMzg4NTJmZjgyNzVjZGRlNjU0ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WimrdkvFcsRtsjuTZqIcGvN7elCbRADPkehWRs5e73A">
> 
> The fix detailed in this thread is only applicable to React Native 0.73+

I'm on     `"react-native": "0.73.4"`

**Comment by araphiel-nf** [comment]
Seems like the patch isn't being applied. May need to check that your postinstall script is being executed

**Comment by ksairi** [comment]
I applied mentioned [patch](https://github.com/react-native-datetimepicker/datetimepicker/issues/866#issuecomment-1983199168)
```
patch -p1 -i ~/Downloads/@react-native-community+datetimepicker+7.6.2.patch
patching file 'node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerShadowView.m'
```
and still get this error:
```
Compiling @react-native-community/datetimepicker Pods/RNDateTimePicker » RNDateTimePickerShadowView.m
[RUN_FASTLANE] 
❌  (/var/folders/69/gql48z9j083grv9d3z46nmxr0000gn/T/eas-build-local-nodejs/95b2ac39-ef5b-4156-96b5-8f784d3c24c9/build/apps/moves-app/node_modules/@react-native-community/datetimepicker/ios/RNDateTimePickerShadowView.m:8:41)

   6 | {
   7 |   if (self = [super init]) {
>  8 |     YGNodeSetMeasureFunc(self.yogaNode, RNDateTimePickerShadowViewMeasure);
     |                                         ^ incompatible function pointer types passing 'YGSize ' (aka 'struct YGSize (struct YGNode *, float, enum YGMeasureMode, float, enum YGMeasureMode)') to parameter of type 'YGMeasureFunc' (aka 'struct YGSize (*)(const struct YGNode *, float, enum YGMeasureMode, float, enum YGMeasureMode)') [-Wincompatible-function-pointer-types]
   9 |   }
  10 |   return self;
  11 | }

**Comment by johnnyxbell** [comment]
Do we have an ETA on a fix? I use expo and I locally build the the apps and it's been failing.

**Comment by WangTao-CD** [comment]
> Do we have an ETA on a fix? I use expo and I locally build the the apps and it's been failing.

same for me, so I restarted my Mac, it worked.

**Comment by blimatech** [comment]
> Same, I changed YGNodeRef to YGNodeConstRef in RNDateTimePickerShadowView.m line 44 (in function RNDateTimePickerShadowViewMeasure) and everything seems back to normal :)

Thanks. It worked for me also.

**Comment by marcelwinter04** [comment]
> > > But i did notice when running eas build locally im getting this issue. <img alt="image" width="844" src="https://private-user-images.githubusercontent.com/36937039/311109551-352c3362-51ed-42fe-a68a-cf7ca71f0134.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNzY1NTksIm5iZiI6MTcxMDE3NjI1OSwicGF0aCI6Ii8zNjkzNzAzOS8zMTExMDk1NTEtMzUyYzMzNjItNTFlZC00MmZlLWE2OGEtY2Y3Y2E3MWYwMTM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDE2NTczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjYjVmMDNkYWE0MTZkNTQ1OGJiNTRlZTljMGIxODdjZDY1YmFjN2ExNTQyMzg4NTJmZjgyNzVjZGRlNjU0ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WimrdkvFcsRtsjuTZqIcGvN7elCbRADPkehWRs5e73A">
> > 
> > 
> > The fix detailed in this thread is only applicable to React Native 0.73+
> 
> I'm on `"react-native": "0.73.4"`

https://github.com/react-native-datetimepicker/datetimepicker/pull/868#issuecomment-1983201760

you created a patch? worked for me after i did.

**Comment by AngrySquirrell** [comment]
Hey, I have the same issue but the fix doesn't work for me... I changed the type of the node variable to the YGNodeConstRef as advised but the error keeps reappearing

**Comment by marcelwinter04** [comment]
> Hey, I have the same issue but the fix doesn't work for me... I changed the type of the node variable to the YGNodeConstRef as advised but the error keeps reappearing

I think you need to create a patch from the package. Because otherwise '''eas build''' just pulls the current package from npm.
https://medium.com/@PreetamGahlot/implement-patch-packages-in-react-native-mobile-app-61f651a7dec1

**Comment by AngrySquirrell** [comment]
> > Hey, I have the same issue but the fix doesn't work for me... I changed the type of the node variable to the YGNodeConstRef as advised but the error keeps reappearing
> 
> I think you need to create a patch from the package. Because otherwise '''eas build''' just pulls the current package from npm. https://medium.com/@PreetamGahlot/implement-patch-packages-in-react-native-mobile-app-61f651a7dec1

You're a legend !! Thank you sooo much

**Comment by Chbilalramzan** [comment]
> Same, I changed YGNodeRef to YGNodeConstRef in RNDateTimePickerShadowView.m line 44 (in function RNDateTimePickerShadowViewMeasure) and everything seems back to normal :)

Worked for me.  Thank you

**Comment by vonovak** [comment]
:tada: This issue has been resolved in version 7.6.3 :tada:

If this package helps you, consider [sponsoring us](https://github.com/sponsors/react-native-datetimepicker)! :rocket:

**Comment by cytryn** [comment]
Updated package to `"@react-native-community/datetimepicker": "7.6.3",` and it fixed the issue for me, thanks!

**Comment by radeno** [comment]
This change breaks RN 0.71. When i changed back to `YGNodeRef` it was able to build with Xcode 15.3

**Comment by araphiel-nf** [comment]
Given this change is tied to RN 0.73 — it might be a good idea to consider this a breaking change

Starting a [version support table](https://github.com/software-mansion/react-native-gesture-handler?tab=readme-ov-file#react-native-support) on the README.md might be a good first issue for someone to pick up

**Comment by rjuevesano** [comment]
<img width="1005" alt="image" src="https://github.com/react-native-datetimepicker/datetimepicker/assets/4033035/a0c4386b-eb0c-4884-9499-8a41c529fabc">

I'm still having an issue here.

```
react-native: 0.71.8

@react-native-community/datetimepicker: 7.6.3
```

**Comment by rjuevesano** [comment]
> Same, I changed YGNodeRef to YGNodeConstRef in RNDateTimePickerShadowView.m line 44 (in function RNDateTimePickerShadowViewMeasure) and everything seems back to normal :)

So I changed back to `YGNodeRef` and it works.

**Comment by ainanabilahh** [comment]
> > Same, I changed YGNodeRef to YGNodeConstRef in RNDateTimePickerShadowView.m line 44 (in function RNDateTimePickerShadowViewMeasure) and everything seems back to normal :)
> 
> So I changed back to `YGNodeRef` and it works.

Same for me

**Comment by namcancode** [comment]
> > Same, I changed YGNodeRef to YGNodeConstRef in RNDateTimePickerShadowView.m line 44 (in function RNDateTimePickerShadowViewMeasure) and everything seems back to normal :)
> 
> So I changed back to `YGNodeRef` and it works.

Lol. it worked

**Comment by jpmoyn** [comment]
@vonovak The latest version is not working. `YGNodeConstRef` in line 44 seems to be the issue.

**Comment by ethras** [comment]
> @vonovak The latest version is not working. `YGNodeConstRef` in line 44 seems to be the issue.

Please read above

**Comment by IronBlossom** [comment]
> 🎉 This issue has been resolved in version 7.6.3 🎉
> 
> If this package helps you, consider [sponsoring us](https://github.com/sponsors/react-native-datetimepicker)! 🚀

Works!! (although `expo-doctor@1.5.0` is yelling )
- SDK: **50.0.14**
- Xcode: **15.3**

**Comment by ryanjwessel** [comment]
> > @vonovak The latest version is not working. `YGNodeConstRef` in line 44 seems to be the issue.
> 
> Please read above
> 
> **v7.6.3 only applies to RN 0.73**

I am observing this issue on RN 0.69.*. We are running 7.6.3 for this package and Xcode 15.3. This change appears to affect more versions of React Native than specified.

**Comment by andreiCrisan55** [comment]
> > > @vonovak The latest version is not working. `YGNodeConstRef` in line 44 seems to be the issue.
> > 
> > 
> > Please read above
> > **v7.6.3 only applies to RN 0.73**
> 
> I am observing this issue on RN 0.69.*. We are running 7.6.3 for this package and Xcode 15.3. This change appears to affect more versions of React Native than specified.

I think he was referring that the fix only applies to RN 0.73 setups

**Comment by ryanjwessel** [comment]
My apologies, I misread the thread. Thanks for clarifying, I'll try this again once I'm upgraded to 0.73.*

**Comment by radulescuandrew** [comment]
Confirm upgrading to 7.6.3 fixed it. Cheers 🍻

**Comment by pavlo-tretiak** [comment]
Upgraded to 7.6.4.

Now it's vice versa 😅 🤡

`incompatible function pointer types passing 'YGSize (YGNodeConstRef, float, YGMeasureMode, float, YGMeasureMode)' (aka 'struct YGSize (const struct YGNode *, float, enum YGMeasureMode, float, enum YGMeasureMode)') to parameter of type 'YGMeasureFunc' (aka 'struct YGSize (*)(struct YGNode *, float, enum YGMeasureMode, float, enum YGMeasureMode)') [-Wincompatible-function-pointer-types]`

Changing YGNodeConstRef back to YGNodeRef fixed the problem.

**Comment by aaparicio87** [comment]
Same error that @pavlo-tretiak 
`incompatible function pointer types passing 'YGSize (YGNodeConstRef, float, YGMeasureMode, float, YGMeasureMode)' (aka 'struct YGSize (const struct YGNode *, float, enum YGMeasureMode, float, enum YGMeasureMode)') to parameter of type 'YGMeasureFunc' (aka 'struct YGSize (*)(struct YGNode *, float, enum YGMeasureMode, float, enum YGMeasureMode)') [-Wincompatible-function-pointer-types]

    YGNodeSetMeasureFunc(self.yogaNode, RNDateTimePickerShadowViewMeasure);`

Any solution?

**Comment by kodaraj** [comment]
Just upgrading to 7.7.0 worked for me. 

`eas build -p ios --local`

```
"expo": "^50.0.14",
"@react-native-community/datetimepicker": "^7.7.0",
"react-native": "0.73.6",
```

**Comment by aaparicio87** [comment]
Seems to be a problem of platform, because I have React Native 0.72

**Comment by christophby** [comment]
Issue still exists:
* react-native 0.72.13
* @react-native-community/datetimepicker 7.7.0

**Comment by ils-nazirh** [comment]
> This change breaks RN 0.71. When i changed back to `YGNodeRef` it was able to build with Xcode 15.3

Thanks, it worked

**Comment by tylim88** [comment]
@react-native-community/datetimepicker: 8.0.0
react-native: 0.73.6

works

**Comment by GerardjRincon** [comment]
> Same, I changed YGNodeRef to YGNodeConstRef in RNDateTimePickerShadowView.m line 44 (in function RNDateTimePickerShadowViewMeasure) and everything seems back to normal :)

In my case it was the opposite I had to change YGNodeRef to YGNodeRef

**Comment by OguzEkinci** [comment]
> Upgraded to 7.6.4.
> 
> Now it's vice versa 😅 🤡
> 
> `incompatible function pointer types passing 'YGSize (YGNodeConstRef, float, YGMeasureMode, float, YGMeasureMode)' (aka 'struct YGSize (const struct YGNode *, float, enum YGMeasureMode, float, enum YGMeasureMode)') to parameter of type 'YGMeasureFunc' (aka 'struct YGSize (*)(struct YGNode *, float, enum YGMeasureMode, float, enum YGMeasureMode)') [-Wincompatible-function-pointer-types]`
> 
> Changing YGNodeConstRef back to YGNodeRef fixed the problem.

ahahaha lol, it's working really v8.0

**Comment by max-arias** [comment]
This is still an issue:

```
"@react-native-community/datetimepicker": "8.0.0",
...
"react-native": "0.74.1",
```

```
// ../RNDateTimePickerShadowView.m

...@react-native-community/datetimepicker/ios/RNDateTimePickerShadowView.m:8:41 Incompatible function pointer types passing 'YGSize (YGNodeRef, float, YGMeasureMode, float, YGMeasureMode)' (aka 'struct YGSize (struct YGNode *, float, enum YGMeasureMode, float, enum YGMeasureMode)') to parameter of type 'YGMeasureFunc' (aka 'struct YGSize (*)(const struct YGNode *, float, enum YGMeasureMode, float, enum YGMeasureMode)')
```

Is the workaround manually patching the library?

**Comment by sinonodd** [comment]
I faced the same issue
![image](https://github.com/react-native-datetimepicker/datetimepicker/assets/51862788/c7c1c282-0d2a-473b-a600-99fa8d2a7941)

Updated  from `"@react-native-community/datetimepicker": "7.6.1`" to `"@react-native-community/datetimepicker": "7.6.3"`
and it worked 🪄

**Comment by friederbluemle** [comment]
I just ran into this issue as well, and after some trial and error, I can confirm 7.6.3+ is breaking RN 0.72 (and below?), while 7.6.2 still works. It can be traced back to #868, merged and released with [`v7.6.3`](https://github.com/react-native-datetimepicker/datetimepicker/releases/tag/v7.6.3) on March 18, 2024.
As @araphiel-nf noted above, this should probably have been a breaking change (i.e. major semver). But since the issue was at least in part affected by an "external" tool update (Xcode 15.3), it's a tricky situation. If possible, it should have been implemented in some backwards compatible way, and released as a follow up _patch_ release (e.g. 7.6.5 and 7.7.1).
Currently, the major version 6 series appears to be partially compatible with RN <=0.72 and partially with RN 0.73+:

| react-native | datetimepicker |
| --- | --- |
| <=0.72 | <=7.6.2 |
| 0.73+ | 7.6.3+ |

**Comment by blodyle** [comment]
Hi all 👋 
It seems there was some sort of regression from a couple months back since right now I had to change from `YGNodeConstRef`  to `YGNodeRef` which is the exact opposite solution from this one (https://github.com/react-native-datetimepicker/datetimepicker/issues/866#issuecomment-1980375427)

Is there any way you could reopen this issue (or create another one) in order to address this? Thanks!

**Comment by devalnor** [comment]
+1

**Comment by dconlisk** [comment]
+1

**Comment by Devdannnny** [comment]
> I faced the same issue ![image](https://private-user-images.githubusercontent.com/51862788/329560258-c7c1c282-0d2a-473b-a600-99fa8d2a7941.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMjA4NDUsIm5iZiI6MTcxNjEyMDU0NSwicGF0aCI6Ii81MTg2Mjc4OC8zMjk1NjAyNTgtYzdjMWMyODItMGQyYS00NzNiLWE2MDAtOTlmYThkMmE3OTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDEyMDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzZmRiZjZiMTk0NjlmZTZhMDY2OTM3MDFhOWNjMGE5YzMxOTc2YjFhNDJhZmU5ZjliMGM0Y2U3MmQyOTA0YjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oqABJK2z5Le0QvMrPXN6m7h7c6qTMk5kEkEKnI60KSE)
> 
> Updated from `"@react-native-community/datetimepicker": "7.6.1`" to `"@react-native-community/datetimepicker": "7.6.3"` and it worked 🪄

This works!!!

**Comment by harshithvemulas** [comment]
> I just ran into this issue as well, and after some trial and error, I can confirm 7.6.3+ is breaking RN 0.72 (and below?), while 7.6.2 still works. It can be traced back to #868, merged and released with [`v7.6.3`](https://github.com/react-native-datetimepicker/datetimepicker/releases/tag/v7.6.3) on March 18, 2024. As @araphiel-nf noted above, this should probably have been considered a breaking change (i.e. major semver). But since the issue was at least in part affected by an "external" tool update (Xcode 15.3), it's a tricky situation. If possible, it should have been implemented in some backwards compatible way, and released as a follow up _patch_ release (e.g. 7.6.5 and 7.7.1). Currently, the major version 6 series appears to be partially compatible with RN <=0.72 and partially with RN 0.73+:
> 
> react-native	datetimepicker
> <=0.72	<=7.6.2
> 0.73+	7.6.3+

This worked for me, I was using RN 0.72 downgraded datetimepicker to 7.6.2 from 7.6.4 and it worked

**Comment by imamrobani** [comment]
> > Same, I changed YGNodeRef to YGNodeConstRef in RNDateTimePickerShadowView.m line 44 (in function RNDateTimePickerShadowViewMeasure) and everything seems back to normal :)
> 
> So I changed back to `YGNodeRef` and it works.

I think this issue back in version `8.0.1`

"react-native": "0.72.14",
"@react-native-community/datetimepicker": "^8.0.1",

Works for me to change back to `YGNodeRef`

**Comment by shivanip-iprogrammer** [comment]
> YGNodeConstRef

same issue, still facing

**Comment by Rajaram10** [comment]
I am using "react-native": "0.71.7",
"@react-native-community/datetimepicker": "7.6.3",
Xcode: 15.4,
and i went with "YGNodeRef" instead of "YGNodeConstRef"
I am able to publish the app.

**Comment by KubilayKartega** [comment]
whelp its broken again. I suspect Xcode 15.4 update. Using
"react-native": "0.72.10",
tried both
"@react-native-community/datetimepicker": "^8.1.1",
and 
"@react-native-community/datetimepicker": "^8.0.1",

Incompatible function pointer types passing 'YGSize (YGNodeConstRef, float, YGMeasureMode, float, YGMeasureMode)' (aka 'struct YGSize (const struct YGNode *, float, enum YGMeasureMode, float, enum YGMeasureMode)') to parameter of type 'YGMeasureFunc' (aka 'struct YGSize (*)(struct YGNode *, float, enum YGMeasureMode, float, enum YGMeasureMode)')

when building

**Comment by psychoz971** [comment]
@KubilayKartega I have the same issue. It doesn't work since Xcode 15.4 update :( with "@react-native-community/datetimepicker": "^8.1.1"

**Comment by astmuhammadadil** [comment]
> Same, I changed YGNodeRef to YGNodeConstRef in RNDateTimePickerShadowView.m line 44 (in function RNDateTimePickerShadowViewMeasure) and everything seems back to normal :)

I did the opposite of this, and it resolved my issue.

**Comment by usmanabid94** [comment]
This worked for me I have used the latest 8.2.0 and still faced the same issue with it.

> > Same, I changed YGNodeRef to YGNodeConstRef in RNDateTimePickerShadowView.m line 44 (in function RNDateTimePickerShadowViewMeasure) and everything seems back to normal :)
> 
> I did the opposite of this, and it resolved my issue.

**Comment by Gentlekboy** [comment]
> Same, I changed YGNodeRef to YGNodeConstRef in RNDateTimePickerShadowView.m line 44 (in function RNDateTimePickerShadowViewMeasure) and everything seems back to normal :)

The opposite worked for me. I changed YGNodeConstRef to YGNodeRef.

**Comment by DusanDigitalWare** [comment]
Any update on this, is the only solution to use patch-package?

**Comment by AkramSyed002** [comment]
in xcode 16.2     "react-native": "0.72.4" for static YGSize RNDateTimePickerShadowViewMeasure(YGNodeRef node, float width, YGMeasureMode widthMode, float height, YGMeasureMode heightMode)

works for me
